service: comp

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  profile: kk
  region: ap-northeast-1
  memorySize: 128

package:
  individually: true

plugins:
  - serverless-scriptable-plugin

functions:
  hello-world:
    handler: handler
    package:
      artifact: bin/hello-world.zip
    events:
      - http:
          path: /hello
          method: get

custom:
  scriptable:
    hooks:
      before:package:createDeploymentArtifacts:
#       for windows
#        - build-and-zip.ps1
#        for linux like
        - make build
      after:package:createDeploymentArtifacts:
        - echo "Build and packaging complete"
