service: comp

provider:
  name: aws
  runtime: provided.al2023
  architecture: arm64
  profile: kk
  region: ap-northeast-1
  memorySize: 128

package:
  individually: true

functions:
  hello-world:
    handler: handler
    package:
      artifact: bin/hello-world.zip
    events:
      - http:
          path: /hello
          method: get
